/**
 * HomeScreen — the landing screen shown when the app opens.
 *
 * Displays:
 * - A welcome message and tonight's sky summary (visible planets, notable stars).
 * - A quick-status card for the user's Tamagotchi pet (hunger, happiness level).
 * - A button to jump straight into the AR sky view.
 * - A "streak" counter showing how many nights in a row the user has gazed.
 *
 * Data sources:
 * - Pet status comes from Redux petSlice.
 * - Tonight's sky summary is generated by CelestialService using current GPS + time.
 */

import React from 'react';
import { View, Text, StyleSheet } from 'react-native';

export default function HomeScreen({ navigation }) {
  // TODO: Read pet state from Redux store.
  // TODO: Call CelestialService.getVisibleObjectsTonight() for the sky summary.
  // TODO: Render pet status card, sky summary, and AR launch button.
  return (
    <View style={styles.container}>
      <Text>HomeScreen — TODO</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0a0a1a',
  },
});
